name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:

  dump_context:
    name: dump context
    runs-on: ubuntu-latest
    steps:
    - name: print GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: print job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: print runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 8
    - name: Build with Maven
      run: mvn --no-transfer-progress --batch-mode clean package
    - name: deploy to Google Cloud
      if: success() && github.event_name == 'push'
      run: ./deploy-google-appengine.sh


  automerge:
    runs-on: [ubuntu-latest]
    name: automerge
    needs: [build]
    if: github.base_ref == 'main' && github.actor == 'dependabot[bot]'
    steps:
    - name: merge
      uses: actions/github-script@v3
      with:
        script: |
          github.pulls.merge({
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
            pull_number: context.payload.pull_request.number,
            merge_method: 'squash'
          })
        github-token: ${{secrets.GITHUB_TOKEN}}
