name: Java CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:

  dump_context:
    name: dump context
    runs-on: ubuntu-latest
    steps:
    - name: print GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: print job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: print runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn --batch-mode clean package --file pom.xml
    - name: deploy to Google Cloud
      if: success() && github.event_name == 'push'
      run: ./deploy-google-appengine.sh
